merge

diff --git a/.github/workflows/Merge-to-Main.yml b/.github/workflows/Merge-to-Main.yml
--- a/.github/workflows/Merge-to-Main.yml
+++ b/.github/workflows/Merge-to-Main.yml
@@ -1,17 +1,30 @@
-name: Check pull request source branch
+name: Check Source Branch
 on:
-  pull_request_target:
+  workflow_dispatch:
+  pull_request:
     types:
       - opened
       - reopened
       - synchronize
+
+env:
+  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
 jobs:
-  check-branches:
+  Check_HEAD_Branch:
     runs-on: ubuntu-latest
     steps:
-      - name: Check branches
+      - name: 📢 Verify BASE and HEAD branches
+        shell: pwsh
         run: |
-          if [[ ! ${{ github.head_ref }} =~ ^rc/.* ]] && [ ${{ github.base_ref }} == "main" ]; then
-            echo "Merge requests to main branch are only allowed from dev branch."
-            exit 1
+          if [[  ${{ github.base_ref }} == "main" ]]; then
+            if [[ ${{ github.head_ref }} =~ ^rc/.*  ||  ${{ github.head_ref }} =~ ^hfc/.* ]]; then
+              echo "🚀📣 Ready to merge"
+            else
+                body="📢 Friendly reminder:  Merge requests to main branch are only allowed from rc/** or hfc/** branches."
+                echo "$body"
+                gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "$body"
+                echo "::error::${{ github.head_ref }} is not allowed to merge directly into main" && exit 1;
+            fi
           fi
+          Write-Host "github.event.pull_request.user.login"
